#!/bin/bash
set -e
set -x
(cd ~/go/src/github.com/u-root/u-root && u-root -defaultsh=rush -uinitcmd=/bbin/console cmds/core/init cmds/core/cat cmds/core/pci cmds/core/ls cmds/core/io cmds/core/mknod cmds/core/msr cmds/exp/rush/ cmds/exp/console )
(cd ~/AMD64/linux && cp /tmp/initramfs.linux_amd64.cpio . && make && cp arch/x86/boot/bzImage ~/oreboot/src/mainboard/amd/romecrb/orebootkernel)
as -o start.o start.S
objcopy -O binary start.o start.bin
PAYLOAD_A=orebootkernel make
go run patch.go
echo start.bin@ff0000
echo this to run qemu: qemu-system-x86_64 -m 3072m -nographic -s -S -monitor /dev/pts/3 -serial /dev/tty -bios bios16.bin
exit 0
reset
echo hit return for qemu, or ^c to break out
read i
qemu-system-x86_64 -m 3072m -nographic -s -S -monitor /dev/pts/3 -serial /dev/tty -bios bios16.bin
